spring.application.name=backend

# Server
server.port=8080
server.servlet.context-path=/api

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/splitmate
spring.datasource.username=root
spring.datasource.password=root123

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# JWT
jwt.secret=splitmate-super-secret-key-change-in-production-min-256-bits
jwt.expiration=86400000

# Flyway - disable since we created tables manually
spring.flyway.enabled=false

# CORS
app.cors.allowed-origins=http://localhost:5173

# Logging
logging.level.com.splitmate=INFO

# Gmail SMTP Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=splitmateapp2025@gmail.com
spring.mail.password=bjxrzmycgfwhefxn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# App base URL
app.base-url=http://localhost:5173
